### ISSUE TITLE
CSS 格式错误

### ISSUE THREAD

**Issue by CNChestnut** [SpeedyOrc-C/HoYo-Glyphs#18]
这是我的 CSS 文件。
 ```css
@font-face {
  font-family: "ZZZ-B";
  src: url(".\ZZZNeue-VariantB-0.003.otf") format("otf");
}
```
当我加上 `format` 时，字体无法正常加载。
但是我去掉 `format` 或者改成 `format('woff')` 或者 `format('woff2')` 就可以正常加载。
这是为什么。

目前我已经发现很多的 OTF 字体文件都存在这个问题，因为不显示导致我以为是其他地方出了问题，排查了好久发现是这个问题。

看了 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@font-face#%E6%B3%A8%E6%84%8F]) 我应该没搞错什么。
